clean up job rewrite

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,7 +4,7 @@ orbs:
 
 commands:
   destroy-environment:
-    description: Destroy back-end and front-end cloudformation stacks given a workflow ID. 
+    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     steps:
       - run:
           name: Destroy environments
@@ -15,7 +15,7 @@ commands:
             aws cloudformation delete-stack --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}
 
   revert-migrations:
-    description: Revert the last migration if successfully run in the current workflow.   
+    description: Revert the last migration if successfully run in the current workflow.
     steps:
       - run:
           name: Revert migrations
@@ -27,10 +27,9 @@ commands:
                 cd ~/project/backend
                 npm install
                 npm run migrations:revert
-            fi        
+            fi
 
 jobs:
-
   ###############
   build-frontend:
     docker:
@@ -60,12 +59,12 @@ jobs:
       - run:
           name: Back-end build
           command: |
-             cd backend
-             npm install
-             npm run build
+            cd backend
+            npm install
+            npm run build
       - save_cache:
           paths: [backend/node_modules]
-          key: backend-build  
+          key: backend-build
   ###############
   test-frontend:
     docker:
@@ -98,7 +97,7 @@ jobs:
   ###############
   scan-frontend:
     docker:
-       - image: cimg/node:13.8.0
+      - image: cimg/node:13.8.0
     steps:
       - checkout
       - restore_cache:
@@ -114,7 +113,7 @@ jobs:
   ###############
   scan-backend:
     docker:
-       - image: cimg/node:13.8.0
+      - image: cimg/node:13.8.0
     steps:
       - checkout
       - restore_cache:
@@ -136,7 +135,7 @@ jobs:
   ###############
   deploy-infrastructure:
     docker:
-      - image: amazon/aws-cli 
+      - image: amazon/aws-cli
     steps:
       - checkout
       - run: yum install -y tar gzip
@@ -147,7 +146,7 @@ jobs:
               --template-file .circleci/files/backend.yml \
               --tags project=udapeople-p3 \
               --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} \
-              --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7} 
+              --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7}
       - run:
           name: Ensure front-end infrastructure exist
           command: |
@@ -155,7 +154,7 @@ jobs:
               --template-file .circleci/files/frontend.yml \
               --tags project=udapeople-p3 \
               --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7} \
-              --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7}   
+              --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7}
       - run:
           name: Add back-end ip to ansible inventory
           command: |
@@ -191,7 +190,7 @@ jobs:
           command: |
             cd .circleci/ansible
             ansible-playbook -i inventory.txt configure-server.yml
-      - destroy-environment    
+      - destroy-environment
   ###############
   run-migrations:
     docker:
@@ -222,18 +221,18 @@ jobs:
     docker:
       - image: cimg/aws:2022.06
     steps:
-      - checkout 
-     
+      - checkout
+
       - run:
           name: Install tar
           command: |
-           sudo apt update
-           sudo apt install tar
+            sudo apt update
+            sudo apt install tar
       - run:
           name: Install node & npm
           command: |
-             sudo apt install nodejs 
-             sudo apt install npm
+            sudo apt install nodejs 
+            sudo apt install npm
       - attach_workspace:
           at: ~/
       - run:
@@ -249,7 +248,7 @@ jobs:
             echo "API_URL = ${API_URL}"
             echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
             cat frontend/.env
-        
+
       - run:
           name: Deploy frontend objects
           command: |
@@ -260,7 +259,7 @@ jobs:
             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
       - destroy-environment
       - revert-migrations
-   ###############
+    ###############
   deploy-backend:
     docker:
       - image: cimg/aws:2022.06
@@ -292,7 +291,7 @@ jobs:
             cp artifact.tar.gz .circleci/ansible/roles/deploy/files
       - run:
           name: Deploy backend
-          command: |    
+          command: |
             cd .circleci/ansible
             echo "Contents  of the inventory.txt file is -------"
             cat inventory.txt
@@ -303,7 +302,7 @@ jobs:
     docker:
       - image: cimg/aws:2022.06
     steps:
-      - checkout 
+      - checkout
       - run:
           name: Get backend url
           command: |
@@ -335,21 +334,21 @@ jobs:
       - run:
           name: Frontend smoke test.
           command: |
-              URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
-              echo ${URL} 
-              if curl -s ${URL} | grep "Welcome"
-              then
-                exit 0
-              else
-                exit 1
-              fi
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+              exit 0
+            else
+              exit 1
+            fi
       - destroy-environment
-      - revert-migrations 
+      - revert-migrations
   cloudfront-update:
     docker:
       - image: cimg/aws:2022.06
     steps:
-      - checkout 
+      - checkout
       - run:
           name: Update cloudfront distribution
           command: |
@@ -359,28 +358,33 @@ jobs:
             --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
             --tags project=udapeople-p3
   cleanup:
-      docker:
-        - image: cimg/aws:2022.06
-      steps:
-        - checkout              
-        - run:
-            name: Get old stack workflow id & Remove old stacks and files
-            command: |
-              export OldWorkflowID=$(aws cloudformation \
-              list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-              --no-paginate --output text)
-              echo OldWorkflowID: "${OldWorkflowID}"
-              echo CIRCLE_WORKFLOW_ID:0:7 "${CIRCLE_WORKFLOW_ID:0:7}"
-              export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
-              --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
-              echo Stack names: "${STACKS[@]}"
-              if [[ "${OldWorkflowID}" =~ "${STACKS[@]}"  ]]
-              then
-                aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
-                aws s3 rb s3://${OldWorkflowID} --force 
-                aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
-                aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
-              fi
+    docker:
+      - image: cimg/aws:2022.06
+    steps:
+      - checkout
+      - run:
+          name: Get old stack workflow id & Remove old stacks and files
+          command: |
+            # Fetch the Old workflow ID
+             export OldWorkflowID=$(aws cloudformation \
+                     list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+                     --no-paginate --output text)
+             echo OldWorkflowID: "${OldWorkflowID}"
+             echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
+             # Fetch the stack names          
+             export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
+                     --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
+             echo Stack names: "${STACKS[@]}"  
+             if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "${OldWorkflowID}" ]]
+             then
+             '----------------start cleaning-----------------------'
+               aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+               aws s3 rb s3://${OldWorkflowID} --force 
+               aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+               aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+             else
+              echo '----------------cannot clean-----------------------'
+             fi
 workflows:
   devops-p3-2200:
     jobs:
@@ -389,7 +393,7 @@ workflows:
       - test-frontend:
           requires: [build-frontend]
       - test-backend:
-          requires: [build-backend]   
+          requires: [build-backend]
       - scan-backend:
           requires: [build-backend]
       - scan-frontend:
@@ -413,6 +417,3 @@ workflows:
           requires: [smoke-test]
       - cleanup:
           requires: [cloudfront-update]
-
-
-          
